# Generated by Django 4.2.5 on 2023-09-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
