# Generated by Django 4.2.5 on 2023-09-30 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_items', '0004_alter_order_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_date']},
        ),
    ]
